// @startuml ee

abstract AnimationController {
    # Animator animator
    # string currentAnimation

    # void ChangeAnimation(string animation, float crossfade = 0.2f)
    # void PlayAnimation(string animation)
}

abstract Observer {
    + {abstract} void ObserverUpdate(GameObject subject)
}