name: Build Project and Publish to itch.io

on:
  push:
    tags:
      - 'windows_v*'

jobs:
  build:
    name: Build Project and Publish to itch.io ✨
    runs-on: ubuntu-latest

    concurrency: 
      group: unity-build
      cancel-in-progress: true

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.56f1 # Version Unity

      # Zip the build
      - name: Zip the Windows build
        run: |
          cd build/StandaloneWindows64
          zip -r ../../Build-Windows.zip .
          cd ../..

      # Upload to itch.io
      - name: Push build to itch.io via Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/dl/latest/linux-amd64.zip
          unzip butler.zip -d butler
          chmod +x butler/butler/butler
          ./butler/butler/butler login --api-key ${{ secrets.BUTLER_API_KEY }}
          ./butler/butler/butler push build/StandaloneWindows64/ tonuser/tonjeu:windows
